Проверка
htmlacademy-htmlcss/2294201-sedona-36 pull request #2
Opened 2023-01-25 09:45 UTC by Artem2022nnr

Прошу проверить прошел ли пулреквест

2023-01-26 08:45 UTC, Kartaviy-arteom requested changes

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +
тут и далее во всем документе, необходимо соблюдать форматирование.
В vscode есть автоформат
On Windows Shift + Alt + F
On Mac Shift + Option + F
On Linux Ctrl + Shift + I

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              <link rel="stylesheet" href="#">
Это тут лишнее

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +                <input type="search">
тут форма не нужна. Это просто ссылка на страницу поиска

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              </li>
лишняя li

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +                Сердечко для лайков
это избранное, кол-во в избранном

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              <button>ХОЧУ СЮДА!</button>
лучше ссылкой

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +        </header>
тут не нужно выделять хедер так

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +                <li class="breadcrumbs-item">
в хлебных крошках есть главная, на пункте гостиницы, ссылка не должна вести на главную. Она там вообще не нужна

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +            <h2>Инфраструктура:</h2>
это фильтры поиска гостниц. Инфраструктура это часть формы

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +                <legend class="catalog-infrastructure-title">Бассейн</legend>
это относится к инфраструктуре. Бассейн это один из чекбоксов

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +            <input class="control-input" type="radio" name="Top hotel">Гостиница
наименование атрибутов, в соответствии с критериями наименований

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +        <input type="range-slider-text" min="0" max="9000">
это тут не нужно и у input нет таких типов

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +        <section class="select-catalog">
нужно добавить заголовок

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +          </a>
это список кнопок, для переключения отображения

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              <input type="button" value="ПОДРОБНЕЕ" accesskey="s">
это ссылка

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              <input type="button" value="В ИЗБРАННОЕ" accesskey="s">
это кнопка

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              <input type="radio" id="star-4" name="rating" value="4">
это не инпут

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +            <form>
тут нет формы

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +              <input type="button" value="ПОДРОБНЕЕ" accesskey="s">
accesskey тебе не нужны. Хотя это не инпут, а ссылка

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +        </section>
нужна пагинация

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +          <input type="email" value="Ваш e-mail">
это форма. К инпуту label

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +          <h2>+7 (812) 812-12-12</h2>
это ссылка

2023-01-26 08:45 UTC, Kartaviy-arteom commented on catalog.html
> +                <span class="visually-hidden">htmlacademy</span>
внутри будет картинка

2023-01-26 08:45 UTC, Kartaviy-arteom commented on index.html
> +      <img class="logo" src="" alt="Логотип Седона">
также отформатировать весь документ

2023-01-26 08:45 UTC, Kartaviy-arteom commented on index.html
> +      <input type="button" value="ПОИСК ГОСТИНИЦЫ В СЕДОНЕ">
кнопка

2023-01-26 08:45 UTC, Kartaviy-arteom commented on index.html
> +        <input type="button" value="Подписаться">
форма, кнопка и лейбл для инпута

2023-01-26 08:45 UTC, Kartaviy-arteom commented on index.html
> +            <ul class="footer-logo-htmlacademy">
списка тут нет

2023-01-27 10:28 UTC, closed without merging

2023-01-27 10:29 UTC, Artem2022nnr commented
Внес правки по замечаниям наставника. И добавил hero.